//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrimeiroCrudWPFEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUTO
    {
        public int IDPRODUTO { get; set; }
        public string DESCRICAO { get; set; }
        public Nullable<int> QUANTIDADE { get; set; }
        public Nullable<decimal> VALOR { get; set; }
        public Nullable<int> ID_CATEGORIA { get; set; }
    
        public virtual CATEGORIA CATEGORIA { get; set; }
    }
}
